### PR TITLE
Bump bitflags to 0.9 and bump version

### PR DESCRIPTION
**Pull request by Eijebong**

### CODE REVIEW

**Comment by Eijebong** [comment]
Ping ? :)

**Comment by KyleMayes** [comment]
Need a major version bump due to the other pull request, the updated version of `bitflags` will be in `v0.19.0`.

**Comment by Eijebong** [comment]
Should I reopen a PR ? You can also just reopen this one and I'll fix the version bump

**Comment by KyleMayes** [comment]
Sorry, I meant I'd bump it myself. `v0.19.0` will be published as soon as my CI builds pass.

**Comment by Eijebong** [comment]
Cool 👍 Thanks

**Comment by KyleMayes** [comment]
Done.

**Pull request closed without merging**
